name: Auto Implement Issue
cat > .github/workflows/auto-implement.yml << 'EOF'
name: Auto Implement Issue

on:
  issues:
    types: [opened, labeled]

jobs:
  auto-implement:
    if: contains(github.event.issue.labels.*.name, 'auto-implement')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Generate code from issue
      run: |
        python .github/scripts/issue-parser.py "${{ github.event.issue.body }}" "${{ github.event.issue.title }}" "${{ github.event.issue.number }}"
        
    - name: Create PR if changes exist
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        if [[ -n $(git status --porcelain) ]]; then
          BRANCH="auto-implement-${{ github.event.issue.number }}"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "Auto-implement: ${{ github.event.issue.title }}"
          git push origin "$BRANCH"
          
          gh pr create --title "Auto-implement: ${{ github.event.issue.title }}" --body "Auto-generated from issue #${{ github.event.issue.number }}" --head "$BRANCH" --base main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
