name: Auto Implement Issue

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  auto-implement:
    if: contains(github.event.issue.labels.*.name, 'auto-implement')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Generate code from issue
      run: |
        python .github/scripts/issue-parser.py \
          "${{ github.event.issue.body }}" \
          "${{ github.event.issue.title }}" \
          "${{ github.event.issue.number }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🤖 Auto-implement: ${{ github.event.issue.title }}"
        title: "🤖 Auto-implement: ${{ github.event.issue.title }}"
        body: |
          Implementação automática da issue #${{ github.event.issue.number }}

          - Código/estrutura gerados pelo bot
          - Revisar antes do merge

          Closes #${{ github.event.issue.number }}
        branch: "auto-implement-${{ github.event.issue.number }}"
        delete-branch: true
        labels: auto-generated, needs-review
